ansible_ssh_proxy_command: >-
  {% if bastion_host is defined and bastion_host != '' %}
  ssh {{ lookup('config', 'DEFAULT_REMOTE_USER') }}@{{ hostvars[bastion_host]['ansible_host'] }}
  -o Port={{ lookup('config', 'DEFAULT_REMOTE_PORT') | default(22) }}
  -o ControlMaster=auto 
  -o ControlPersist=30m
  -o ForwardAgent=yes
  -W %h:%p
  {% endif %}

ansible_ssh_common_args: >-
  {% if bastion_host is defined and bastion_host != '' %}
  -o ProxyCommand="{{ ansible_ssh_proxy_command }}"
  {% endif %}