---
- name: Configure DevSec Hardening
  hosts: bastion
  remote_user: sysadmin
  become: yes
  
  collections:
  - devsec.hardening

  tasks:
    - name: Configure DevSec Hardening
      vars:
        network_ipv6_enable: false
        ssh_allow_tcp_forwarding: 'yes'
        ssh_allow_agent_forwarding: 'yes'
        ssh_server_ports: ['2222']
        ssh_client_port: '2222'
      block:
      - name: Apply DevSec SSH Hardening
        ansible.builtin.import_role:
          name: devsec.hardening.ssh_hardening
      - name: Apply DevSec OS Hardening
        ansible.builtin.import_role:
          name: devsec.hardening.os_hardening