- name: Configure /etc/hosts entries
  hosts: all
  remote_user: sysadmin
  become: yes

  tasks: 
    - name: Configure /etc/hosts entries
      when: hostvars[item]['ansible_ens10'] is defined
      with_items: "{{ groups.all }}"
      block: 
      - name: Add Private IP address of all hosts to hosts.debian.tmpl
        lineinfile:
          dest: /etc/cloud/templates/hosts.debian.tmpl
          line: "{{ hostvars[item]['ansible_ens10']['ipv4']['address'] }} {{ hostvars[item].ansible_hostname }} "
          state: present
      - name: Add Private IP address of all hosts to /etc/hosts
        lineinfile:
          dest: /etc/hosts
          line: "{{ hostvars[item]['ansible_ens10']['ipv4']['address'] }} {{ hostvars[item].ansible_hostname }} "
          state: present
