- name: Configure /etc/hosts entries
  hosts: all
  remote_user: sysadmin
  become: yes

  tasks: 
    - name: Configure knet /etc/hosts entries
      when: hostvars[item]['ansible_knet'] is defined
      block: 
      - name: Add Private IP address of all hosts to hosts.debian.tmpl
        lineinfile:
          dest: /etc/cloud/templates/hosts.debian.tmpl
          line: "{{ hostvars[item]['ansible_knet']['ipv4']['address'] }} {{ hostvars[item].ansible_hostname }} "
          state: present
        with_items: "{{ groups.all }}"
      - name: Add Private IP address of all hosts to /etc/hosts
        lineinfile:
          dest: /etc/hosts
          line: "{{ hostvars[item]['ansible_knet']['ipv4']['address'] }} {{ hostvars[item].ansible_hostname }} "
          state: present
        with_items: "{{ groups.all }}"

    - name: Configure bnet /etc/hosts entries
      when: hostvars[item]['ansible_bnet'] is defined
      block: 
      - name: Add Private IP address of all hosts to hosts.debian.tmpl
        lineinfile:
          dest: /etc/cloud/templates/hosts.debian.tmpl
          line: "{{ hostvars[item]['ansible_bnet']['ipv4']['address'] }} {{ hostvars[item].ansible_hostname }} "
          state: present
        with_items: "{{ groups.all }}"
      - name: Add Private IP address of all hosts to /etc/hosts
        lineinfile:
          dest: /etc/hosts
          line: "{{ hostvars[item]['ansible_bnet']['ipv4']['address'] }} {{ hostvars[item].ansible_hostname }} "
          state: present
        with_items: "{{ groups.all }}"
