- name: Configure Worker
  hosts: s0haproxy
  remote_user: sysadmin
  become: yes

  collections:
  - labrats_work.modules_ansible

  tasks:  
  - ansible.builtin.import_role:
      name: labrats_work.modules_ansible.haproxy
    vars:
      haproxy_config: "{{ lookup('ansible.builtin.template', 'files/haproxy/haproxy.cfg.j2') }}"