---
- name: Configure DevSec Hardening
  hosts: all
  remote_user: sysadmin
  become: yes
  
  collections:
  - devsec.hardening

  tasks:
    - name: Configure DevSec Hardening
      vars:
        sysctl_overwrite:
          net.ipv4.ip_forward: 1
        network_ipv6_enable: false
        ssh_server_ports: ['2222']
        ssh_client_port: '2222'
      block: 
      - name: Apply DevSec OS Hardening
        ansible.builtin.import_role:
          name: devsec.hardening.os_hardening

      - name: Apply DevSec SSH Hardening
        ansible.builtin.import_role:
          name: devsec.hardening.ssh_hardening