- name: Configure Nodes
  hosts: master:worker
  remote_user: sysadmin
  become: yes

  collections:
  - labrats_work.modules_ansible
  
  tasks:
    - name: Configure DevSec Hardening
      vars:
        sysctl_overwrite:
          net.ipv4.ip_forward: 1
        network_ipv6_enable: false
        ssh_server_ports: ['2222']
        ssh_client_port: '2222'
      block:
        - name: Apply DevSec SSH Hardening
          ansible.builtin.import_role:
            name: devsec.hardening.ssh_hardening
        # - name: Apply DevSec OS Hardening
        #   ansible.builtin.import_role:
        #     name: devsec.hardening.os_hardening
    - name: Configure Kubernetes Dependencies
      block:
        - name: Install Containerd
          ansible.builtin.import_role:
            name: labrats_work.modules_ansible.containerd
        - name: Install OpenISCI
          ansible.builtin.import_role:
            name: labrats_work.modules_ansible.open_isci
        - name: Install Kubernetes Packages
          ansible.builtin.import_role:
            name: labrats_work.modules_ansible.kubernetes_node
        
