- name: Configure Master
  hosts: master
  remote_user: sysadmin
  become: yes

  collections:
  - labrats_work.modules_ansible
  
  vars:
    kubernetes_iface: "knet"
    kubernetes:
      clusterName: c0
      bindPort: 6443
      kubernetesVersion: "1.25.0"
      serviceSubnet: "10.96.0.0/12"
      podSubnet: "10.244.0.0/16"

  tasks:      
  - ansible.builtin.import_role:
      name: labrats_work.modules_ansible.kubernetes_init
    vars:
      nodetype: master
      kubeadm_init:
        nodeRegistration: 
          taints: null
          name: "{{ ansible_facts['fqdn'] }}"
          criSocket: "unix:///var/run/containerd/containerd.sock"
        localAPIEndpoint:
          advertiseAddress: "{{ ansible_facts[kubernetes_iface]['ipv4']['address'] }}"
          bindPort: "{{ kubernetes['bindPort'] }}"
        networking:
          serviceSubnet: "{{ kubernetes['serviceSubnet'] }}"
          podSubnet: "{{ kubernetes['podSubnet'] }}"
          dnsDomain: cluster.local
        kubernetesVersion: "{{ kubernetes['kubernetesVersion'] }}"
        controlPlaneEndpoint: "{{ ansible_facts[kubernetes_iface]['ipv4']['address'] }}:{{ kubernetes['bindPort'] }}"
        apiServer:
          certSANs:
          - "{{ ansible_facts['fqdn'] }}"
          timeoutForControlPlane: 10m0s
        certificatesDir: "/etc/kubernetes/pki"
        clusterName: "{{ kubernetes['clusterName'] }}"
        controllerManager: {}
        scheduler: {}
