- name: Configure Worker
  hosts: worker
  remote_user: sysadmin
  become: yes

  collections:
  - tomp736.ansible_awesome

  tasks:  
  - ansible.builtin.import_role:
      name: tomp736.ansible_awesome.kubernetes_worker
    vars:
      master_node: 'c0m0'