name: 'Deploy E2E Test'

on:
  workflow_dispatch:
  pull_request:
    branches:    
      - main  
      - dev
  push:
    paths:
      - '!.github/workflows/deploy.yml'
      - '!**/README.md'

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/workspace-deploy.yml
    with:
      TF_WORKSPACE: ${{ github.actor }}_${{ github.base_ref || 'dev' }}
      TF_MODULES_REF: ${{ github.base_ref || 'dev' }}
      ANSIBLE_MODULES_REF: ${{ github.base_ref || 'dev' }}
      FLUX_WORKSPACE: ${{ github.base_ref || 'dev' }}
      TERRAFORM_APPLY: true
      ANSIBLE_APPLY: true
    secrets: inherit  
