name: 'Deploy TF Apply Test'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      TF_WORKSPACE: none
      TF_MODULES_REF: ${{ github.base_ref || 'dev' }}
      ANSIBLE_MODULES_REF: ${{ github.base_ref || 'dev' }}
      FLUX_WORKSPACE: ${{ github.base_ref || 'dev' }}
      TERRAFORM_APPLY: true
      ANSIBLE_APPLY: false
      LIFETIME: 1m
    secrets: inherit  
