name: 'Deploy E2E Test'

on:
  workflow_dispatch:
  pull_request:
    branches:    
      - main  
      - dev
  push:
    paths:
      - '!.github/workflows/deploy.yml'
      - '!**/README.md'

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      TF_WORKSPACE: none
      TF_MODULES_REF: ${{ github.head_ref || github.ref_name }}
      FLUX_WORKSPACE: ${{ github.head_ref || github.ref_name }}
      TERRAFORM_APPLY: 'true'
      ANSIBLE_APPLY: 'true'
      LIFETIME: 1m
    secrets: inherit  
