name: 'Deploy'

on:
  workflow_dispatch:
    inputs:
      TF_WORKSPACE:
        type: choice
        description: Terraform Remote Workspace
        required: true
        options: 
        - "none"
        - tomp736
      TF_MODULES_REF:
        type: choice
        description: Terraform Modules Ref
        required: true
        options: 
        - main
        - dev
      FLUX_WORKSPACE:
        type: choice
        description: Terraform Remote Workspace
        required: true
        options: 
        - tomp736
      TERRAFORM_APPLY:
        type: boolean
        description: Apply Terraform
        required: true
        default: false
      ANSIBLE_APPLY:
        type: boolean
        description: Apply Ansible
        required: true
        default: false
      LIFETIME:
        type: choice
        description: Lifetime of cluster (minutes).
        required: true
        options:
        - 1m
        - 30m
        - 60m

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  RESOURCE_PREFIX: "${{ github.event.inputs.TF_WORKSPACE == "none" && github.sha || format('{0}-{1}-', github.event.inputs.TF_WORKSPACE, (github.head_ref || github.ref_name)) }}

permissions:
  contents: read

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: "${{ github.event.inputs.TF_WORKSPACE }}"
    concurrency: 
      group: ${{ github.event.inputs.TF_WORKSPACE == "none" && github.sha || format('{0}-{1}', github.event.inputs.TF_WORKSPACE, (github.head_ref || github.ref_name)) }}
      cancel-in-progress: false      
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_NAME }}
    - 
      name: Create keypair for test.
      run: |
        ssh-keygen -t ed25519 -N '' -f id_ed25519
        xargs -a id_ed25519 -I{} -d'\n' echo ::add-mask::{}
        xargs -a id_ed25519.pub -I{} -d'\n' echo ::add-mask::{}
    - 
      name: Load keypair for test.
      run: |
        echo "Loading KEYFILE \"id_ed25519\" into GITHUB_ENV."
        echo 'KEYFILE<<EOF' >> $GITHUB_ENV
        cat id_ed25519 >> $GITHUB_ENV
        echo EOF >> $GITHUB_ENV

        echo "Loading PUBKEYFILE \"id_ed25519.pub\" into GITHUB_ENV."
        echo 'PUBKEYFILE<<EOF' >> $GITHUB_ENV
        cat id_ed25519.pub >> $GITHUB_ENV
        echo EOF >> $GITHUB_ENV
    - 
      name: Create default.tfvars file
      run: |
        echo "hcloud_token = \"${{ secrets.HCLOUD_TOKEN }}\"" >> default.tfvars
        echo "public_key = \"${{ env.PUBKEYFILE }}\"" >> default.tfvars
    - 
      if: ${{ github.event.inputs.TF_WORKSPACE }} != "none"
      name: Apply changes for remote backend
      run: |
        echo "Create default.tfrc file"
        echo "# default.tfrc" > default.tfrc
        echo "credentials \"app.terraform.io\" {" >> default.tfrc
        echo "  token = \"${{ secrets.TFCLOUD_TOKEN }}\"" >> default.tfrc
        echo "}" >> default.tfrc

        echo "Create config.remote.tfbackend"
        echo "# config.remote.tfbackend" > config.remote.tfbackend
        echo "workspaces { name = \"kubernetes_at_hetzner_${{ github.event.inputs.TF_WORKSPACE }}\" }" >> config.remote.tfbackend
        echo "hostname     = \"app.terraform.io\"" >> config.remote.tfbackend
        echo "organization = \"labrats-work\"" >> config.remote.tfbackend 

        echo "Create config.remote.tfbackend"
        sed -i 's|local|remote|g' providers.tf
    - 
      name: Update prefix for resources.
      run: |
        sed -i 's|{prefix}|${{ env.RESOURCE_PREFIX }}|g' files/config.json
    - 
      name: Terraform Plan
      uses: labrats-work/action-terraform@main
      with:
        verb: plan
        init: yes
        varsFile: default.tfvars
        planFile: tfplan
        backendConfigFile: config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      name: Terraform Apply
      if: github.event.inputs.TERRAFORM_APPLY == 'true'
      uses: labrats-work/action-terraform@main
      with:
        verb: apply
        init: yes
        planFile: tfplan
        backendConfigFile: config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      if: github.event.inputs.TERRAFORM_APPLY == 'true' && github.event.inputs.ANSIBLE_APPLY == 'true'
      name: Run playbook
      uses: labrats-work/action-ansible@main
      with:
        workingDirectory: ./ansible
      env:
        FLUX_INIT_OWNER: "tomp736"
        FLUX_INIT_REPO: "kubernetes_at_hetzner_flux"
        FLUX_INIT_PATH: "clusters/${{ github.event.inputs.FLUX_WORKSPACE }}"
        FLUX_INIT_TOKEN: "${{ secrets.FLUX_INIT_TOKEN_2 }}"
    - 
      name: Cluster Timeout
      run: |
        echo "Will destroy cluster in ${{ github.event.inputs.LIFETIME }}."
        sleep ${{ github.event.inputs.LIFETIME }}
    - 
      if: always() && github.event.inputs.TERRAFORM_APPLY == 'true'
      id: destroy
      continue-on-error: true
      name: Terraform Destroy
      uses: labrats-work/action-terraform@main
      with:
        verb: destroy
        init: yes
        varsFile: default.tfvars
        backendConfigFile: config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      if: always() && github.event.inputs.TERRAFORM_APPLY == 'true' && steps.destroy.outcome == 'failure'
      id: destroy2
      continue-on-error: true
      name: Terraform Destroy
      uses: labrats-work/action-terraform@main
      with:
        verb: destroy
        init: yes
        varsFile: default.tfvars
        backendConfigFile: config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      if: always() && github.event.inputs.TERRAFORM_APPLY == 'true' && steps.destroy2.outcome == 'failure'
      id: destroy3
      continue-on-error: true
      name: Terraform Destroy
      uses: labrats-work/action-terraform@main
      with:
        verb: destroy
        init: yes
        varsFile: default.tfvars
        backendConfigFile: config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    