name: 'Deploy E2E Test'

on:
  pull_request:
    branches:    
      - main  
      - dev
  push:
    paths:
      - '!.github/workflows/deploy.yml'
      - '!**/README.md'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  RESOURCE_PREFIX: "${{ github.head_ref || github.ref_name }}-"

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    inputs:
      TF_WORKSPACE: ""
      FLUX_WORKSPACE: ${{ github.head_ref || github.ref_name }}
      TF_MODULES_REF: ${{ github.head_ref || github.ref_name }}
      TERRAFORM_APPLY: true
      ANSIBLE_APPLY: true
      LIFETIME: 1m
    secrets: inherit  
