name: 'Deploy TF Plan Test'

on:
  workflow_dispatch:
  push:
    ignore-branches:
    - main
    - dev
    paths:
      - '!**/README.md'

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      TF_WORKSPACE: none
      TF_MODULES_REF: ${{ github.base_ref || 'dev' }}
      ANSIBLE_MODULES_REF: ${{ github.base_ref || 'dev' }}
      FLUX_WORKSPACE: ${{ github.base_ref || 'dev' }}
      TERRAFORM_APPLY: false
      ANSIBLE_APPLY: false
      LIFETIME: 1m
    secrets: inherit  
