name: 'Deploy E2E Test'

on:
  workflow_dispatch:
    inputs:
      TERRAFORM_APPLY:
        type: boolean
        description: Apply Terraform
        required: true
        default: true
      ANSIBLE_APPLY:
        type: boolean
        description: Apply Ansible
        required: true
        default: true
  pull_request:
    branches:    
      - main  
      - dev
  push:
    paths:
      - '!.github/workflows/deploy.yml'
      - '!**/README.md'

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/workspace-deploy.yml
    with:
      ENVIRONMENT: ${{ github.actor }}-${{ github.head_ref || 'dev' }}
      TF_MODULES_REF: ${{ github.base_ref || 'dev' }}
      ANSIBLE_MODULES_REF: ${{ github.base_ref || 'dev' }}
      FLUX_WORKSPACE: ${{ github.base_ref || 'dev' }}
      TERRAFORM_APPLY: ${{ inputs.TERRAFORM_APPLY || true }}
      ANSIBLE_APPLY: ${{ inputs.ANSIBLE_APPLY || true }}
      PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOJfG+Q279TtMZcYGoyF5Z3TRuQlGc3QtGP4r7M3A7Hh u0@prt-dev-01"
    secrets: inherit  
  # deploy:
  #   uses: ./.github/workflows/workspace-deploy.yml
  #   with:
  #     ENVIRONMENT: ${{ github.actor }}-${{ github.head_ref || 'dev' }}
  #     TF_MODULES_REF: ${{ github.head_ref || 'dev' }}
  #     ANSIBLE_MODULES_REF: ${{ github.head_ref || 'dev' }}
  #     FLUX_WORKSPACE: ${{ github.head_ref || 'dev' }}
  #     TERRAFORM_APPLY: ${{ inputs.TERRAFORM_APPLY || true }}
  #     ANSIBLE_APPLY: ${{ inputs.ANSIBLE_APPLY || true }}
  #     PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOJfG+Q279TtMZcYGoyF5Z3TRuQlGc3QtGP4r7M3A7Hh u0@prt-dev-01"
  #   secrets: inherit  
