name: 'Terraform'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    defaults:
      run:
        shell: bash

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_NAME }}
    - 
      name: Create vars file.
      run: |
        echo "hcloud_token = \"${{ secrets.HCLOUD_TOKEN }}\"" >> default.tfvars
    - 
      name: Terraform Plan
      uses: labrats-work/action-terraform@main
      with:
        verb: plan
        init: yes
        varsFile: secrets/${{ env.BRANCH_NAME }}.tfvars
        planFile: tfplan
        sshKey: ${{ secrets.SSH_PRIVATE_KEY }}
      env:
        TF_TOKEN: ${{ secrets.TFCLOUD_TOKEN }}
    - 
      name: Terraform Apply
      uses: labrats-work/action-terraform@main
      with:
        verb: apply
        init: yes
        planFile: tfplan
        sshKey: ${{ secrets.SSH_PRIVATE_KEY }}
      env:
        TF_TOKEN: ${{ secrets.TFCLOUD_TOKEN }}
    - 
      name: Mask IPs
      run: xargs -a node_ips -I{} -d'\n' echo ::add-mask::{}
    - 
      name: Run playbook
      uses: labrats-work/action-ansible@main
      with:
        workingDirectory: ./ansible
        sshKey: ${{secrets.SSH_PRIVATE_KEY}}
    