name: 'Terraform'

on:
  push:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_NAME }}
    - 
      name: Create default.tfvars file
      run: |
        echo "hcloud_token = \"${{ secrets.HCLOUD_TOKEN }}\"" >> default.tfvars
    - 
      name: Create default.tfrc file
      run: |
        echo "# default.tfrc" > default.tfrc
        echo "credentials \"app.terraform.io\" {" >> default.tfrc
        echo "  token = \"${{ secrets.TFCLOUD_TOKEN }}\"" >> default.tfrc
        echo "}" >> default.tfrc
    - 
      name: Terraform Plan
      uses: labrats-work/action-terraform@main
      with:
        verb: plan
        init: yes
        varsFile: default.tfvars
        planFile: tfplan
        sshKey: ${{ secrets.SSH_PRIVATE_KEY }}
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    # - 
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: tfplan
    #     path: tfplan
    - 
      if: github.ref == 'refs/heads/main'
      name: Terraform Apply
      uses: labrats-work/action-terraform@main
      with:
        verb: apply
        init: yes
        planFile: tfplan
        sshKey: ${{ secrets.SSH_PRIVATE_KEY }}
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
    - 
      if: github.ref == 'refs/heads/main'
      name: Run playbook
      uses: labrats-work/action-ansible@main
      with:
        workingDirectory: ./ansible
        sshKey: ${{secrets.SSH_PRIVATE_KEY}}
    