name: 'Terraform'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    defaults:
      run:
        shell: bash

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH_NAME }}
    - 
      name: Checkout secrets repository.
      uses: actions/checkout@v3
      with:
        repository: tomp736/awesome_kubernetes_secrets
        token: ${{ secrets.SECRETS_PAT }}
        path: ./secrets
        ref: main
    - 
      name: Terraform Plan
      uses: labrats-work/action-terraform@main
      with:
        verb: plan
        init: yes
        varsFile: secrets/${{ env.BRANCH_NAME }}.tfvars
        planFile: tfplan
    - 
      name: Terraform Apply
      uses: labrats-work/action-terraform@main
      with:
        verb: apply
        init: yes
        planFile: tfplan
    - 
      name: Commit secrets repository changes.
      uses: EndBug/add-and-commit@v9
      if: always()
      with:
        cwd: './secrets'
    - 
      name: Copy inventory
      run: cp secrets/${{ env.BRANCH_NAME }}_inventory ansible/inventory
    - 
      name: Run playbook
      uses: labrats-work/action-ansible@main
      with:
        workingDirectory: ./ansible
        sshKey: ${{secrets.SSH_PRIVATE_KEY}}
    