name: 'Terraform Destroy'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - 
      name: Create vars file.
      run: |
        echo "hcloud_token = \"${{ secrets.HCLOUD_TOKEN }}\"" >> default.tfvars
    - 
      name: Terraform Plan
      uses: labrats-work/action-terraform@main
      with:
        verb: destroy
        init: yes
        varsFile: default.tfvars
      env:
        TF_TOKEN: ${{ secrets.TFCLOUD_TOKEN }}