name: 'Terraform Destroy'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - 
      name: Checkout secrets repository.
      uses: actions/checkout@v3
      with:
        repository: tomp736/awesome_kubernetes_secrets
        token: ${{ secrets.SECRETS_PAT }}
        path: ./secrets
        ref: main
    - 
      name: Terraform Plan
      uses: labrats-work/action-terraform@main
      with:
        verb: destroy
        init: yes
        varsFile: secrets/main.tfvars
    - 
      name: Commit secrets repository changes.
      uses: EndBug/add-and-commit@v9
      if: always()
      with:
        cwd: './secrets'
