name: 'Workspace Cleanup'

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  cleanup_check:
    name: 'Cleanup'
    runs-on: ubuntu-latest
    outputs:
      tomp736-dev: ${{ steps.cleanup_check.outputs.tomp736-dev }}
      tomp736-main: ${{ steps.cleanup_check.outputs.tomp736-main }}
    steps:
      - name: Check if workspace last update was over 30 minutes ago.
        id: cleanup_check_tomp736-dev
        run: |
          curl \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/tomp736/kubernetes_at_hetzner/deployments?environment=tomp736-dev > deployments.json

          DATE_DEP=$(jq -r '.[].updated_at' deployments.json | sort -r | head -n 1)
          DATE_EXP=$(date -d "$DATE_DEP + 30 minutes" +%s)
          DATE_NOW=$(date -u +%s)

          if [ $DATE_EXP -le $DATE_NOW ]
          then 
            echo 'tomp736-dev=1' >> $GITHUB_OUTPUT
          else
            echo 'tomp736-dev=0' >> $GITHUB_OUTPUT
          fi
      - name: Check if workspace last update was over 30 minutes ago.
        id: cleanup_check_tomp736-main
        run: |
          curl \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/tomp736/kubernetes_at_hetzner/deployments?environment=tomp736-main > deployments.json

          DATE_DEP=$(jq -r '.[].updated_at' deployments.json | sort -r | head -n 1)
          DATE_EXP=$(date -d "$DATE_DEP + 30 minutes" +%s)
          DATE_NOW=$(date -u +%s)

          if [ $DATE_EXP -le $DATE_NOW ]
          then 
            echo 'tomp736-main=1' >> $GITHUB_OUTPUT
          else
            echo 'tomp736-main=0' >> $GITHUB_OUTPUT
          fi
          
  cleanup_tomp736-dev:
    if: needs.cleanup_check.outputs.tomp736-dev == '1'
    needs: cleanup_check
    uses: ./.github/workflows/workspace-destroy.yml
    with:
      TF_WORKSPACE: tomp736-dev
      TF_MODULES_REF: 'dev'
    secrets: inherit  
          
  cleanup_tomp736-main:
    if: needs.cleanup_check.outputs.tomp736-main == '1'
    needs: cleanup_check
    uses: ./.github/workflows/workspace-destroy.yml
    with:
      TF_WORKSPACE: tomp736-main
      TF_MODULES_REF: 'main'
    secrets: inherit  
