name: 'Workspace Cleanup'

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  cleanup_check:
    name: 'Cleanup'
    runs-on: ubuntu-latest
    outputs:
      cleanup: ${{ steps.cleanup_check.outputs.tomp736_dev }}
      cleanup: ${{ steps.cleanup_check.outputs.tomp736_main }}
    steps:
      - name: Check if workspace last update was over 30 minutes ago.
        id: cleanup_check_tomp736_dev
        run: |
          curl \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/tomp736/kubernetes_at_hetzner/deployments?environment=tomp736_dev > deployments.json

          DATE_DEP=$(jq -r '.[].updated_at' deployments.json | sort -r | head -n 1)
          DATE_EXP=$(date -d "$DATE_DEP + 30 minutes" +%s)
          DATE_NOW=$(date -u +%s)

          if [ $DATE_EXP -le $DATE_NOW ]
          then 
            echo 'tomp736_dev=1' >> $GITHUB_OUTPUT
          else
            echo 'tomp736_dev=0' >> $GITHUB_OUTPUT
          fi
      - name: Check if workspace last update was over 30 minutes ago.
        id: cleanup_check_tomp736_main
        run: |
          curl \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/tomp736/kubernetes_at_hetzner/deployments?environment=tomp736_main > deployments.json

          DATE_DEP=$(jq -r '.[].updated_at' deployments.json | sort -r | head -n 1)
          DATE_EXP=$(date -d "$DATE_DEP + 30 minutes" +%s)
          DATE_NOW=$(date -u +%s)

          if [ $DATE_EXP -le $DATE_NOW ]
          then 
            echo 'tomp736_main=1' >> $GITHUB_OUTPUT
          else
            echo 'tomp736_main=0' >> $GITHUB_OUTPUT
          fi
          
  cleanup_run:
    if: needs.cleanup_check.outputs.tomp736_dev == '1'
    needs: cleanup_check
    uses: ./.github/workflows/workspace-destroy.yml
    with:
      TF_WORKSPACE: tomp736_dev
      TF_MODULES_REF: ${{ github.base_ref || 'dev' }}
      PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOJfG+Q279TtMZcYGoyF5Z3TRuQlGc3QtGP4r7M3A7Hh u0@prt-dev-01"
    secrets: inherit  
          
  cleanup_run:
    if: needs.cleanup_check.outputs.tomp736_main == '1'
    needs: cleanup_check
    uses: ./.github/workflows/workspace-destroy.yml
    with:
      TF_WORKSPACE: tomp736_main
      TF_MODULES_REF: ${{ github.base_ref || 'dev' }}
      PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOJfG+Q279TtMZcYGoyF5Z3TRuQlGc3QtGP4r7M3A7Hh u0@prt-dev-01"
    secrets: inherit  
