name: 'Workspace Destroy'

permissions:
  contents: read

jobs:
  deploy:
    name: 'Destroy'
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    concurrency: 
      group: ${{ inputs.ENVIRONMENT }}
      cancel-in-progress: false      
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Create default.tfvars file
      run: |
        echo "hcloud_token = \"${{ secrets.HCLOUD_TOKEN }}\"" > terraform/default.tfvars
        echo "public_key = \"xxx\"" >> terraform/default.tfvars
    - 
      name: Apply changes for remote backend
      run: |
        echo "Create default.tfrc file"
        echo "# default.tfrc" > terraform/default.tfrc
        echo "credentials \"app.terraform.io\" {" >> terraform/default.tfrc
        echo "  token = \"${{ secrets.TFCLOUD_TOKEN }}\"" >> terraform/default.tfrc
        echo "}" >> terraform/default.tfrc

        echo "Create config.remote.tfbackend"
        echo "# config.remote.tfbackend" > config.remote.tfbackend
        echo "workspaces { name = \"kubernetes_at_hetzner_${{ inputs.ENVIRONMENT }}\" }" >> config.remote.tfbackend
        echo "hostname     = \"app.terraform.io\"" >> config.remote.tfbackend
        echo "organization = \"labrats-work\"" >> config.remote.tfbackend 

        echo "Create config.remote.tfbackend"
        sed -i 's|local|remote|g' terraform/providers.tf
    - 
      name: Update Terraform Ref
      run: |
        sed -i 's|modules-terraform.git//modules/cloud-init?ref=main|modules-terraform.git//modules/cloud-init?ref=${{ inputs.TF_MODULES_REF }}|g' terraform/main.tf
        sed -i 's|modules-terraform.git//modules/hetzner/network?ref=main|modules-terraform.git//modules/hetzner/network?ref=${{ inputs.TF_MODULES_REF }}|g' terraform/main.tf
        sed -i 's|modules-terraform.git//modules/hetzner/node?ref=main|modules-terraform.git//modules/hetzner/node?ref=${{ inputs.TF_MODULES_REF }}|g' terraform/main.tf
    - 
      id: destroy
      continue-on-error: true
      name: Terraform Destroy
      uses: labrats-work/action-terraform@main
      with:
        chdir: terraform
        verb: destroy
        init: yes
        varsFile: default.tfvars
        backendConfigFile: config.remote.tfbackend
      env:
        TF_CLI_CONFIG_FILE: default.tfrc
        KEYFILE: ${{ secrets.SSH_KEY }}

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        description: Terraform Remote Workspace
        required: true
      TF_MODULES_REF:
        type: string
        description: Terraform Modules Ref
        required: true